---
title: "demo1"
author: "Grace Levin"
date: "9/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}

library(sf)
library(tidyverse)
library(ggthemes)
library(ggspatial)
```

```{r, echo= FALSE}
nbhoods <- st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/3525b0ee6e6b427f9aab5d0a1d0a1a28_0.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D", quiet = TRUE)

sea_level_rise <- st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/74692fe1b9b24f3c9419cd61b87e4e3b_5.kml?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D", quiet = TRUE)

hospitals <- st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/8f1e5741a4ee4c0f82925d17aab3c002_2.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D", quiet = TRUE)

```

```{r, echo=FALSE}
ggplot(nbhoods) +
  geom_sf(fill = "NA", color = "grey") +
  geom_sf(data = sea_level_rise, fill = "lightblue", color = "black", size = 0.5, alpha = 0.6) + 
  geom_sf(data = hospitals, color = "red", size = 2)

```

```{r, echo=FALSE}
ggplot(nbhoods) +
  geom_sf(fill = "NA", color = "grey") +
  geom_sf(data = sea_level_rise, color = NA, alpha = 0.6, aes(fill = "Sea Level Rise")) + 
  geom_sf(data = hospitals, size = 1.5, alpha = 0.5, aes(color = "Hospitals")) +
  scale_fill_manual(values= "light blue", name ="") +
  scale_color_manual(values = c("orange"), name = "") +
  theme_void()



```


```{r, echo=FALSE}
ggplot() +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight") +
  geom_sf(data = sea_level_rise, color = NA, alpha = 0.6, aes(fill = "Sea Level Rise")) + 
  geom_sf(data = hospitals, size = 1.5, alpha = 0.5, aes(color = "Hospitals")) +
  scale_fill_manual(values= "light blue", name ="") +
  scale_color_manual(values = c("orange"), name = "")+
  theme_void()+
  labs(caption = "Map tiles and data from OpenStreetMap")
  



```

